import type { PublicDisplayMode, UiLanguage } from "./types";

const ACCOUNT_COPY = {
  ru: {
    navAccount: "Аккаунт",
    auth: {
      createTitle: "Создай аккаунт для сезона",
      createText: "Аккаунт хранится на сервере, а не только на этом телефоне. Ты сможешь войти снова, изменить профиль и восстановить доступ позже.",
      loginTitle: "Войти в аккаунт",
      loginText: "Используй email и пароль, чтобы вернуться к своему профилю и бюллетеням.",
      resetTitle: "Восстановление доступа",
      resetText: "Мы создадим ссылку для сброса пароля. В локальном режиме она покажется прямо здесь.",
      email: "Email",
      password: "Пароль",
      newPassword: "Новый пароль",
      currentPassword: "Текущий пароль",
      firstName: "Имя",
      lastName: "Фамилия",
      displayName: "Публичное имя",
      displayNameHint: "Можно оставить пустым и показывать обычные имя и фамилию.",
      emoji: "Эмодзи или короткий бейдж",
      publicDisplayOptIn: "Показывать моё имя и аватар в таблицах комнаты и на экранах",
      privacyAccepted: "Я согласен с политикой обработки персональных данных и правилами хранения необходимых cookies/local storage",
      createAccount: "Создать аккаунт",
      signIn: "Войти",
      requestReset: "Отправить ссылку",
      applyReset: "Сбросить пароль",
      signOut: "Выйти",
      switchToCreate: "Создать аккаунт",
      switchToLogin: "У меня уже есть аккаунт",
      switchToReset: "Забыл пароль",
      previewReset: "Тестовая ссылка для локального режима",
      passwordRule: "Минимум 8 символов.",
      manageAccount: "Управлять аккаунтом",
      loggedInAs: "Ты вошёл как",
    },
    account: {
      title: "Профиль и доступ",
      subtitle: "Здесь можно обновить публичное имя, аватар, пароль и настройки приватности.",
      profileTitle: "Профиль",
      profileText: "Имя и фамилия можно хранить полностью, а для публичных таблиц выбрать более приватный режим отображения.",
      securityTitle: "Безопасность",
      securityText: "Меняй пароль заранее, чтобы через год не вспоминать старый в последний момент.",
      avatarTitle: "Аватар",
      avatarText: "Для таблиц результатов лучше всего работает круглый аватар с emoji-бейджем.",
      privacyTitle: "Приватность",
      privacyText: "Политика и заметки по обязательным cookies/local storage доступны по ссылкам ниже.",
      dangerTitle: "Удаление",
      dangerText: "Удаление аккаунта уберёт твой профиль, сессии и результаты из комнат.",
      saveProfile: "Сохранить профиль",
      uploadAvatar: "Загрузить аватар",
      removeAvatar: "Убрать аватар",
      changePassword: "Сменить пароль",
      deleteAccount: "Удалить аккаунт",
      saved: "Профиль обновлён.",
      avatarSaved: "Аватар обновлён.",
      avatarRemoved: "Аватар удалён.",
      passwordChanged: "Пароль изменён.",
      accountDeleted: "Аккаунт удалён.",
      localProcessing: "Обязательные cookies и local storage используются только для входа, черновиков, языка и работы комнаты.",
      privacyLink: "Политика обработки данных",
      cookiesLink: "Хранение cookies и local storage",
    },
    publicDisplayModes: {
      full_name: "Полное имя",
      first_name_last_initial: "Имя и первая буква фамилии",
      display_name: "Публичное имя",
    } satisfies Record<PublicDisplayMode, string>,
  },
  en: {
    navAccount: "Account",
    auth: {
      createTitle: "Create your season account",
      createText: "This account lives on the server, not only on this phone. You can sign in again later, update your profile, and recover access if needed.",
      loginTitle: "Sign in to your account",
      loginText: "Use your email and password to get back to your profile and ballots.",
      resetTitle: "Recover access",
      resetText: "We will create a password reset link. In local mode it appears right here.",
      email: "Email",
      password: "Password",
      newPassword: "New password",
      currentPassword: "Current password",
      firstName: "First name",
      lastName: "Last name",
      displayName: "Public display name",
      displayNameHint: "You can leave this empty and use your regular first and last name.",
      emoji: "Emoji or short badge",
      publicDisplayOptIn: "Show my name and avatar on room leaderboards and display screens",
      privacyAccepted: "I agree to the privacy notice and the required cookies/local storage notice",
      createAccount: "Create account",
      signIn: "Sign in",
      requestReset: "Send reset link",
      applyReset: "Reset password",
      signOut: "Sign out",
      switchToCreate: "Create account",
      switchToLogin: "I already have an account",
      switchToReset: "Forgot password",
      previewReset: "Local reset link preview",
      passwordRule: "At least 8 characters.",
      manageAccount: "Manage account",
      loggedInAs: "Signed in as",
    },
    account: {
      title: "Profile and access",
      subtitle: "Update your public name, avatar, password, and privacy settings here.",
      profileTitle: "Profile",
      profileText: "You can keep your full first and last name in the account and still choose a more private public mode for scoreboards.",
      securityTitle: "Security",
      securityText: "Change your password before the season so you do not need to remember an old one a year later.",
      avatarTitle: "Avatar",
      avatarText: "A round avatar with an emoji badge works best for compact room leaderboards.",
      privacyTitle: "Privacy",
      privacyText: "The policy and required cookies/local storage note are available below.",
      dangerTitle: "Delete",
      dangerText: "Deleting the account removes your profile, sessions, and room results.",
      saveProfile: "Save profile",
      uploadAvatar: "Upload avatar",
      removeAvatar: "Remove avatar",
      changePassword: "Change password",
      deleteAccount: "Delete account",
      saved: "Profile updated.",
      avatarSaved: "Avatar updated.",
      avatarRemoved: "Avatar removed.",
      passwordChanged: "Password changed.",
      accountDeleted: "Account deleted.",
      localProcessing: "Required cookies and local storage are used only for sign-in, drafts, language selection, and room functionality.",
      privacyLink: "Privacy notice",
      cookiesLink: "Cookies and local storage",
    },
    publicDisplayModes: {
      full_name: "Full name",
      first_name_last_initial: "First name + last initial",
      display_name: "Public display name",
    } satisfies Record<PublicDisplayMode, string>,
  },
} as const;

export function getAccountCopy(language: UiLanguage) {
  return ACCOUNT_COPY[language];
}
